color1="#182538"  # background
color2="#49586d"  # current line / muted gray
color3="#eff3f8"  # foreground / light text
color4="#6cabda"  # mid blue
color5="#a7d0ec"  # bright blue
color6="#61a7d6"  # primary blue
color7="#969293"  # muted red/gray
color8="#8da1c8"  # soft purple-blue
color9="#c3c1c1"  # bright gray
color10="#d8dee9" # light gray-blue
