exec-once = uwsm app -- hypridle
exec-once = uwsm app -- hyprlock
exec-once = uwsm app -- mako
exec-once = uwsm app -- swayosd-server

exec-once = nvibrant 150 400
exec-once = wl-clipboard
exec-once = waybar
exec-once = hyprpaper
exec-once = quickshell
exec-once = [workspace 10 silent] spotify
exec-once = [workspace 9 silent] discord

exec-once = sleep 5 && openrgb --startminimized --profile ~/.config/OpenRGB/cat.orp
