$sky_dark_solid = rgba(89b4faff)
$sky_shadow = rgba(11111baa)
$sky_border = rgba(b4befeff)          # active border
$sky_inactive_border = rgba(0,0,0,0)  # fully transparent inactive border
$groupbar_text = rgba(89dcebff)

general {
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    layout = dwindle
    border_size = 1
    col.active_border = $sky_border
    col.inactive_border = rgba(585b70ff)
}

decoration {
    rounding = 6
	  dim_special = 0.0
    active_opacity = 1.0
    inactive_opacity = 0.95

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        # enabled = true
        # size = 8
        # passes = 1
        vibrancy = 0.1696
        #
        enabled = true
        size = 8
        passes = 1
        new_optimizations = true
        xray = false
		    contrast = 0.7
		    brightness = 0.5
		    noise = 0.1
		    # vibrancy = 80
		    vibrancy_darkness = 0.0
		    special = true
    }
}
group {
    col.border_active = rgba(fab387ff)
    col.border_inactive = rgba(585b70ff)
    # auto_group = true
    groupbar {
        # rounding = 10
        font_family = JetBrainsMono Nerd Font Mono
        font_size = 10
        height = 30
        text_offset = -1
        indicator_gap = 1
        indicator_height = 1
        col.active = rgba(a6e3a1ff)
        col.inactive = rgba(181825ff)
        text_color = rgba(cdd6f4ff)
        text_color_inactive = rgba(6c7086ff)
        gaps_in = 0
        gaps_out = 0
        # font_weight_active = bold
        # font_weight_inactive = normal
    }
}
