background = #1b1c1d
foreground = #f1f0f6
cursor-color = #e2201f
cursor-text = #1b1c1d

palette = 0=#e2201f
palette = 1=#e2201f
palette = 2=#e2201f
palette = 3=#e2201f
palette = 4=#4a90e2
palette = 5=#e2201f
palette = 6=#e2201f
palette = 7=#f1f0f6

palette = 8=#303038
palette = 9=#e2201f
palette = 10=#303038
palette = 11=#e2201f
palette = 12=#6ab4ff
palette = 13=#e2201f
palette = 14=#303038
palette = 15=#ffffff
